### ISSUE TITLE
Sync/Async and data_selectors

### ISSUE THREAD

**Issue by fwunder** [andygott/Really-Simple-Slideshow#1]
Excellent work!

Just wondering if Jquery Image Loader ( http://www.staticvoid.info/imageLoader/ ) might be useful in loading images. Seems a bit more flexible with sync/async control and setting start point (number of images to load from array before beginning).

Also, thinking forward to reading data_selectors from delimitated file ( url,caption,link_to,effect ).

Again, great work!

**Comment by andygott** [comment]
I've had a quick look at jQuery Image Loader. It appears that it requires jQuery UI, which I'd rather not depend upon with Really Simple Slideshow, as it's intended to be simple and lightweight. 

Also, given the current scope of Really Simple Slideshow, I'm not sure there's a use case that would require loading images asynchronously (except, perhaps to speed up a slideshow by loading images faster, but this throws up a plethora of other issues). 

If I'm missing something here, and you see a need for more flexible loading of images, please let me know.

jQuery Image Loader does look useful under other circumstances, however—we could have really used something like this in our recent and ongoing Gooify project, for example, for which we developed something similar.

I like the idea of offering other options for injecting slide data into a slideshow, and this is something we've been thinking about. Early ideas have revolved around loading data with a simple asynchronous GET request, which would allow developers to construct any back end method they liked (flat file, DB, etc), providing the output worked with whatever interface RS Slideshow provided. Would this work for the use case you have in mind?

Thanks for the feedback—really appreciated.
