### ISSUE TITLE
Add Class to Individual Slides

### ISSUE THREAD

**Issue by mfeltrop** [andygott/Really-Simple-Slideshow#10]
I am really enjoying using this jQuery addon. It is really quite beautiful. Thank you for providing it.

I would like to be able to add a class/id to an individual slide or anchor. Is this functionality currently supported?

**Comment by andygott** [comment]
Sorry for the delay in getting back to you on this. I’ve added a new event trigger that allows you to set event handlers to fire when the slide has been created as a jQuery object, but before it is added to the DOM. This allows for adding custom classes (or anything else) to the slide before it is inserted.

You’ll need to grab the latest version (1.4.9) to make this work. Please see this https://gist.github.com/2017922 for some example code. Also, I’ve updated one of the demos to provide a working example.

Hope this helps.

Andy

**Comment by mfeltrop** [comment]
Thank you so much.
