### ISSUE TITLE
slideshow moves to next number before picture is loaded

### ISSUE THREAD

**Issue by jmotive** [andygott/Really-Simple-Slideshow#11]
hi i'm in need of help.  i'm not sure if i did this right but if someone could please help, see http://jmotive.com/cdhtest/works.html.  it moves to the next number before the picture is loaded.  once all the pictures are loaded it works fine, the way it is supposed to.  but in the beginning when pics are not loaded yet, it is a big mess.  please let me know what i am doing wrong.   thanks so so very much!

**Comment by mfeltrop** [comment]
It works fine for me.

**Comment by jmotive** [comment]
Hi, i guess it loads ok sometimes but there is another issue i hope u can help me on this. the caption is full across on the white block and centered on all browsers except Internet explorer.  On IE, the white block doesnt stretch all the way across and it is not centered, it is shifted to the left.  Do u know how I can fix this?
Thanks

**Comment by andygott** [comment]
Sorry for the delay – been busy around here recently!

The latest update (1.4.10) should fix this. The issue occurred when the interval time you set between slides was shorter than the time it takes to load a slide (very large images, very slow connections, very short slide intervals, or a combination). The latest version waits until the image has loaded. Bare in mind that it’s important to keep your images small if you need the slideshow to run quickly on the first cycle.

I haven’t tested, but your IE issue sounds like something to do with `position: absolute` and block level elements. Perhaps try adding `width: 100%` to your caption?

Andy

**Comment by jmotive** [comment]
adding `width: 100%` to the caption worked!  Thanks!!
How do I update to 1.4.10?  Does it mean I would have to redo my webpage?
 Thank you so much again!

On Sun, Mar 11, 2012 at 4:22 PM, Really Simple <
reply@reply.github.com

**Comment by andygott** [comment]
Just download the latest version of this file:

https://github.com/reallysimple/Really-Simple-Slideshow/blob/master/js/jquery.rs.slideshow.js

Put it here:

http://jmotive.com/cdhtest/js/jquery.rs.slideshow.js

And you’re updated.

Andy

**Comment by jmotive** [comment]
A million times thanks! :)

On Sun, Mar 11, 2012 at 6:03 PM, Really Simple <
reply@reply.github.com
