### ISSUE TITLE
Slideshow not progressing beyond slide #2

### ISSUE THREAD

**Issue by saurabhnanda** [andygott/Really-Simple-Slideshow#13]
No matter what I try, the slideshow does not automatically progress beyond slide #2. Clicking on the numbered index or next/previous controls works, but the slide does not progress automatically.

(I'm working off the latest minified version of rs-Slideshow downloaded off Github)

Here's how I'm initializing the slideshow:

```
$('body.itinerary_page .rs-slideshow').rsfSlideshow({
'controls': {
        playPause: {auto: true},
        previousSlide: {auto: true},
        nextSlide: {auto: true},
        index: {auto: true}
},
});
```

Here's what the slideshow markup looks like:

```
 <div id="trip_slideshow" class="rs-slideshow">
    <img class="" src="/system/images/6/itinerary/IMG_1049.JPG?1332271396" width="100%" />
    <span class="slide-caption"></span>
    <ol class="slides">
      <li><a href="/system/images/6/itinerary/IMG_1049.JPG?1332271396" title=""></a></li>
      <li><a href="/system/images/14/itinerary/IMG_0094.JPG?1334433029" title=""></a></li>
      <li><a href="/system/images/16/itinerary/PICT0036.JPG?1334433180" title=""></a></li>
    </ol>
  </div>
```

**Comment by saurabhnanda** [comment]
Any help with this issue? A comment that someone's read this would be appreciated.

**Comment by andygott** [comment]
Sorry for the slow response – been hectic here with client work!

It does appear there’s a bug with the latest release. I’m looking into this now.

**Comment by andygott** [comment]
Now fixed. 838c8557ed8fc2541bde2158af6695033c97a39e

**Comment by saurabhnanda** [comment]
Works! Thanks a lot for fixing this so quickly.
