### ISSUE TITLE
next slide link on image

### ISSUE THREAD

**Issue by fietstouring** [andygott/Really-Simple-Slideshow#17]
how can I make the slideshow advance to the next slide when clicking on the image itself?

**Comment by daka79** [comment]
I'd like some help here too. Anyone?

**Comment by andygott** [comment]
You could bind to the click event on slides and use the `nextSlide` method, like this:

``` javascript
$('#slideshow img').on('click', function(e) {
    e.preventDefault();
    $('#slideshow').rsfSlideshow('nextSlide');
});
```
