### ISSUE TITLE
Don't show controls when slideshow has only one slide

### ISSUE THREAD

**Issue by thdk** [andygott/Really-Simple-Slideshow#28]
When the slidehow contains only a single slide, there is no need to show the controls.

This is how I implement this behavior now using the options: 
$('#slideshow').rsfSlideshow(
        {controls: {
                playPause: { auto: $('#slideshow .slides li').length > 1 },
                previousSlide: { auto: $('#slideshow .slides li').length > 1 },
                nextSlide: { auto: $('#slideshow .slides li').length > 1 },
                index: { auto: $('#slideshow .slides li').length > 1 }
            }
        });

**Comment by andygott** [comment]
I can’t think of a use case where it makes sense to use a slideshow with only one slide. It might be better to count the number of slides before initialising the slideshow, or even better, before loading it at all, and just displaying the single image instead.

Closing this as it isn’t worth adding extra code to cover this use case.
