### ISSUE TITLE
RS Simple slideshow + IE 8.0 + Jquery min > 1.4.2 => not Compatible

### ISSUE THREAD

**Issue by Mart80** [andygott/Really-Simple-Slideshow#3]
Hello, 

I use the last version of the plugin "Really Simple Slideshow" in my website. 
When checking the compatibility among the different browsers, I got the conclusion that it works with Safari 5.0.5 , Firefox 4.0 but IE 8.0 (I did not check other versions of IE)

Here is the error message I got : "Object does not support this property or method. jquery.rs.slideshow.js Line 639 Char 7"

First, I have suspected bad configuration on my side. So, I downloaded your "demo pack and check "simpledemo.html" in the different browsers. I got the same conclusion, it does not work in IE8.0. 

Next step, I wondered why it is compatible with all browsers when I go on your website (http://reallysimpleworks.com/slideshow/) and not when I use the demo-pack?

I finally got the answer : your plugin does not work with IE when the version of jquery is >1.4.2

On your website, jquery.min 1.4.2 is used. In the demo pack, jquery.min 1.6.1 is used.

Other point : when using jquery.min 1.4.2, fade effect does not work in IE 8.0

 Regards, 

Martin

**Comment by andygott** [comment]
HI Martin,

Just pushed an update with a fix. 

Thanks for the heads-up,

Andy

**Comment by Mart80** [comment]
Hi Andy,

Thanks for your quick action!
It works ;-) (but still no fading in IE 8.0)

Martin

2011/5/18 reallysimple <
reply@reply.github.com>
