### ISSUE TITLE
JS Initialization (off) option

### ISSUE THREAD

**Issue by farsider** [andygott/Really-Simple-Slideshow#5]
I've been tweaking the js options to include other objects in the image array (aside from image and caption), and so far it's working great. One issue, however, is the information that populates my array is dynamic from a CRM. After the initial launch, the data loads and cycles great, but I need to find a way to remove the non-java-user dependency on the premier slide. Without access to the array sheet, the default HTML in the data container will always populate slide 1, until it cycles around to array 1. Is adjusting this possible?

**Comment by andygott** [comment]
I'm not clear on what your questions is – could you clarify for me? Are you saying that you have slide data available via JavaScript, but not available to your HTML template? Are you loading from the CRM using JavaScript (AJAX)?

Andy

**Comment by farsider** [comment]
Aye, essentially. The slide data comes through element tags in the slide array (e.g.: img, title, caption, and other content divs I've added) that are changed via the CRM. The data will never be static, and will update every few months. Unfortunately, the CRM cannot alter the content in the slide-container div, which initialises for viewers without js enabled (from my understanding). So, is there a way to have the slide initialise with the first element in the array instead of the slide-container html?

**Comment by andygott** [comment]
This should do what you're looking for:

https://gist.github.com/1012311

Andy
