### ISSUE TITLE
effect: 'fade'

### ISSUE THREAD

**Issue by gshilin** [andygott/Really-Simple-Slideshow#8]
Thank you a lot for the plugin!!!

There is just one thing that would be nice to have. My images have transparent zones. So when fading in a new image, one can see an old one beneath it. When the fading finishes, the old one just disappears. But, because of transparent zones, one can see this disappearing. It would be nice to add something like fade-out for an old image (maybe with duration parameter, zero by default).

**Comment by andygott** [comment]
Hi,

@michaelclegg sent us this cross-fade transition effect just the other day – it may help in your situation. Simply include this code, and then use `effect: 'crossFade'` when you initialize the slideshow.

``` js
$.rsfSlideshow.transitions.crossFade = function($slideshow, $slide) {
    $slide.fadeIn(
        $slideshow.data('rsf_slideshow').settings.transition,
        function() {
            RssPrivateMethods._endTransition($slideshow, $slide);
        });
    $slide.prev().fadeOut(
        $slideshow.data('rsf_slideshow').settings.transition);
}
```

Thanks for getting in touch,

Andy

**Comment by gshilin** [comment]
10x
